### ISSUE TITLE
karma-edge-launcher is no longer on npm

### ISSUE THREAD

**Issue by mickdekkers** [nickmccurdy/karma-edge-launcher#10]
https://www.npmjs.com/package/karma-edge-launcher

**Comment by nickserv** [comment]
I can't remember that well, but I believe I intentionally avoided releasing this due to its lack of stability (I was also waiting for Windows 10 to have its first stable release). If you're still interested in this package and there isn't another good alternative, I'd be happy to update this and release it if I have the time.

**Comment by mickdekkers** [comment]
:+1: I would definitely be interested in this package.
I've looked around but you seem to be the only one to have attempted this.

**Comment by nickserv** [comment]
Sounds good, now that I have an install of Windows 10 after the stable release I will test this out again and see if I can get it to work. While I will close this issue because it's intentionally not on npm yet, I'll try to make it clear if/when this has its first release on npm. Also, let me know if you would like to contribute.

**Comment by mickdekkers** [comment]
I've actually just set up Sauce Labs + Travis CI for my project. While I currently don't have any projects I would be using this package for, I'm still interested in contributing.

**Comment by nickserv** [comment]
That's great, thanks! Please look at this comment on my latest pull request: https://github.com/nicolasmccurdy/karma-edge-launcher/pull/11#issuecomment-150410699

**Comment by nickserv** [comment]
This is now on npm, see the readme.
