### ISSUE TITLE
npm install targets wrong project

### ISSUE THREAD

**Issue by afnpires** [nickmccurdy/karma-edge-launcher#17]
As specified in the Readme I've ran the `npm install karma-edge-launcher --save-dev` to install.

I've configured it in karma browsers to run, but when I run the tests I received the error 

```
21 07 2016 15:01:23.489:ERROR [plugin]: Cannot find plugin "./node_modules/karma-edge-launcher".
  Did you forget to install it?
  npm install .\node_modules/karma-edge-launcher --save-dev
```

I thought this was weird, the install wen't flawlessly so I went to node_modules to check if the karma-edge-launcher is or not installed.
But surprise, surprise it was there, but the folder had no js file, only the `readme.md`, `project.json` and `LICENSE`.

I've open the `project.json` to check for any clue and I found that the `karma-edge-launcher` is associated to this [repository](https://github.com/watilde/karma-edge-launcher) which is not yours.

So how can I install your karma-edge-launcher?

**Comment by nickserv** [comment]
Sorry for the delay. If you use a GitHub repo shorthand instead of a package name, npm will grab a package through GitHub instead of its package registry. You can use this package temporarily with `nicolasmccurdy/karma-edge-launcher`, but please be warned that this is not stable yet and your results may very. If you don't need it to be stable and you just want the latest dev work, I recommend checking out the `use-edge-launcher` branch (see #19).

**Comment by nickserv** [comment]
I temporarily marked this project as private and removed links to the npm package to reduce confusion (since it's a different project though it has the same goal). Hopefully this should be more clear now.

**Comment by nickserv** [comment]
The missing JavaScript file has been fixed, the `karma-edge-launcher` npm package now points to this project.
